version: '2'

services:
  panganudcloud:
    container_name: panganudcloud
    build:
      context: .      
      dockerfile: Dockerfile
    restart: always
    image: panganudcloud:1.042
    volumes:
      - ./bukidnongeoserver_geoserver-data:/usr/src/app/mnt/geoserver/
    ports:
      - 7500:9000
    command: npm run start